export const FORMULARIO_MENU = 'FORMULARIO_MENU' 
export const OBTENER_MENUS = 'OBTENER_MENUS' 
export const AGREGAR_MENU = 'AGREGAR_MENU' 
export const VALIDAR_FORMULARIO = 'VALIDAR_FORMULARIO' 
export const MENU_ACTUAL = ' MENU_ACTUAL'
export const ELIMINAR_MENU = 'ELIMINAR_MENU'
export const MENU_ERROR = 'MENU_ERROR'

export const SECCIONES_MENU = 'SECCIONES_MENU';
export const AGREGAR_SECCION = 'AGREGAR_SECCION';
export const VALIDAR_SECCION = 'VALIDAR_SECCION';
export const ELIMINAR_SECCION = 'ELIMINAR_SECCION'
export const ESTADO_SECCION = "ESTADO_SECCION"
export const SECCION_ACTUAL = "SECCION_ACTUAL";
export const ACTUALIZAR_SECCION = 'ACTUALIZAR_SECCION'
export const LIMPIAR_SECCION = 'LIMPIAR_SECCION'

export const PLATILLOS_SECCION = 'PLATILLOS_SECCION';
export const AGREGAR_PLATILLO = 'AGREGAR_PLATILLO';
export const VALIDAR_PLATILLO = 'VALIDAR_PLATILLO';
export const ELIMINAR_PLATILLO = 'ELIMINAR_PLATILLO'
export const ESTADO_PLATILLO = "ESTADO_PLATILLO"
export const PLATILLO_ACTUAL = "PLATILLO_ACTUAL";
export const ACTUALIZAR_PLATILLO = 'ACTUALIZAR_PLATILLO'
export const LIMPIAR_PLATILLO = 'LIMPIAR_PLATILLO'

export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';


export const REGISTRO_EXISTOSO = "REGISTRO_EXITOSO";
export const REGISTRO_ERROR = "REGISTRO_ERROR";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGIN_EXITOSO = "LOGIN_EXITOSO";
export const CERRAR_SESION = 'CERRAR_SESION';
export const OBTENER_USUARIO = 'OBTENER_USUARIO';
