export const FORMULARIO_RESTAURANTE = "FORMULARIO_RESTAURANTE";
export const OBTENER_RESTAURANTES = "OBTENER_RESTAURANTES";
export const AGREGAR_RESTAURANTE = "AGREGAR_RESTAURANTE";
export const RESTAURANTE_ACTUAL = " RESTAURANTE_ACTUAL";
export const ELIMINAR_RESTAURANTE = "ELIMINAR_RESTAURANTE";
export const RESTAURANTE_ERROR = "RESTAURANTE_ERROR";
export const VALIDAR_FORMULARIO = "VALIDAR_FORMULARIO";

export const MENUS_RESTAURANTE = "MENUS_RESTAURANTE";
export const AGREGAR_MENU = "AGREGAR_MENU";
export const VALIDAR_MENU = "VALIDAR_MENU";
export const ELIMINAR_MENU = "ELIMINAR_MENU";
export const ESTADO_MENU = "ESTADO_MENU";
export const MENU_ACTUAL = "MENU_ACTUAL";
export const MENU_ACTIVO = "MENU_ACTIVO";
export const ACTUALIZAR_MENU = "ACTUALIZAR_MENU";
export const LIMPIAR_MENU = "LIMPIAR_MENU";

export const MESAS_RESTAURANTE = "MESAS_RESTAURANTE";
export const AGREGAR_MESA = "AGREGAR_MESA";
export const VALIDAR_MESA = "VALIDAR_MESA";
export const ELIMINAR_MESA = "ELIMINAR_MESA";
export const ESTADO_MESA = "ESTADO_MESA";
export const MESA_ACTUAL = "MESA_ACTUAL";
export const ACTUALIZAR_MESA = "ACTUALIZAR_MESA";
export const LIMPIAR_MESA = "LIMPIAR_MESA";
export const OBTENER_UNA_MESA = "OBTENER_UNA_MESA";

export const SECCIONES_MENU = "SECCIONES_MENU";
export const AGREGAR_SECCION = "AGREGAR_SECCION";
export const VALIDAR_SECCION = "VALIDAR_SECCION";
export const ELIMINAR_SECCION = "ELIMINAR_SECCION";
export const ESTADO_SECCION = "ESTADO_SECCION";
export const SECCION_ACTUAL = "SECCION_ACTUAL";
export const ACTUALIZAR_SECCION = "ACTUALIZAR_SECCION";
export const LIMPIAR_SECCION = "LIMPIAR_SECCION";

export const PLATILLOS_SECCION = "PLATILLOS_SECCION";
export const AGREGAR_PLATILLO = "AGREGAR_PLATILLO";
export const VALIDAR_PLATILLO = "VALIDAR_PLATILLO";
export const ELIMINAR_PLATILLO = "ELIMINAR_PLATILLO";
export const ESTADO_PLATILLO = "ESTADO_PLATILLO";
export const PLATILLO_ACTUAL = "PLATILLO_ACTUAL";
export const ACTUALIZAR_PLATILLO = "ACTUALIZAR_PLATILLO";
export const LIMPIAR_PLATILLO = "LIMPIAR_PLATILLO";

export const MOSTRAR_ALERTA = "MOSTRAR_ALERTA";
export const OCULTAR_ALERTA = "OCULTAR_ALERTA";

export const REGISTRO_EXISTOSO = "REGISTRO_EXITOSO";
export const REGISTRO_ERROR = "REGISTRO_ERROR";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGIN_EXITOSO = "LOGIN_EXITOSO";
export const CERRAR_SESION = "CERRAR_SESION";
export const OBTENER_USUARIO = "OBTENER_USUARIO";

export const SESIONGENERAL_MESA = "SESIONGENERAL_MESA";
export const AGREGAR_SESIONGENERAL = "AGREGAR_SESIONGENERAL";
export const VALIDAR_SESIONGENERAL = "VALIDAR_SESIONGENERAL";
export const ELIMINAR_SESIONGENERAL = "ELIMINAR_SESIONGENERAL";
export const ESTADO_SESIONGENERAL = "ESTADO_SESIONGENERAL";
export const SESIONGENERAL_ACTUAL = "SESIONGENERAL_ACTUAL";
export const ACTUALIZAR_SESIONGENERAL = "ACTUALIZAR_SESIONGENERAL";
export const LIMPIAR_SESIONGENERAL = "LIMPIAR_SESIONGENERAL";

export const SESIONINDIVIDUAL_SESIONGENERAL = "SESIONINDIVIDUAL_SESIONGENERAL";
export const AGREGAR_SESIONINDIVIDUAL = " AGREGAR_SESIONINDIVIDUAL";
export const VALIDAR_SESIONINDIVIDUAL = "VALIDAR_SESIONINDIVIDUAL";
export const ELIMINAR_SESIONINDIVIDUAL = "ELIMINAR_SESIONINDIVIDUAL";
export const ESTADO_SESIONINDIVIDUAL = "ESTADO_SESIONINDIVIDUAL";
export const SESIONINDIVIDUAL_ACTUAL = "SESIONINDIVIDUAL_ACTUAL";
export const ACTUALIZAR_SESIONINDIVIDUAL = "ACTUALIZAR_SESIONINDIVIDUAL";
export const LIMPIAR_SESIONINDIVIDUAL = "LIMPIAR_SESIONINDIVIDUAL";

export const ORDEN_SESIONINDIVIDUAL = "ORDEN_SESIONINDIVIDUAL";
export const ORDEN_RESTAURANTE = "ORDEN_RESTAURANTE";
export const AGREGAR_ORDEN = " AGREGAR_ORDEN";
export const VALIDAR_ORDEN = "VALIDAR_ORDEN";
export const ELIMINAR_ORDEN = "ELIMINAR_ORDEN";
export const ESTADO_ORDEN = "ESTADO_ORDEN";
export const ORDEN_ACTUAL = "ORDEN_ACTUAL";
export const ACTUALIZAR_ORDEN = "ACTUALIZAR_ORDEN";
export const LIMPIAR_ORDEN = "LIMPIAR_ORDEN";

export const PLATILLOORDENADO_ORDEN = "PLATILLOORDENADO_ORDEN";
export const AGREGAR_PLATILLOORDENADO = " AGREGAR_PLATILLOORDENADO";
export const VALIDAR_PLATILLOORDENADO = "VALIDAR_PLATILLOORDENADO";
export const ELIMINAR_PLATILLOORDENADO = "ELIMINAR_PLATILLOORDENADO";
export const ESTADO_PLATILLOORDENADO = "ESTADO_PLATILLOORDENADO";
export const PLATILLOORDENADO_ACTUAL = "PLATILLOORDENADO_ACTUAL";
export const ACTUALIZAR_PLATILLOORDENADO = "ACTUALIZAR_PLATILLOORDENADO";
export const LIMPIAR_PLATILLOORDENADO = "LIMPIAR_PLATILLOORDENADO";
