export const FORMULARIO_RESTAURANTE = 'FORMULARIO_RESTAURANTE' 
export const OBTENER_RESTAURANTES = 'OBTENER_RESTAURANTES' 
export const AGREGAR_RESTAURANTE = 'AGREGAR_RESTAURANTE' 
export const RESTAURANTE_ACTUAL = ' RESTAURANTE_ACTUAL'
export const ELIMINAR_RESTAURANTE = 'ELIMINAR_RESTAURANTE'
export const RESTAURANTE_ERROR = 'RESTAURANTE_ERROR'
export const VALIDAR_FORMULARIO = 'VALIDAR_FORMULARIO';


export const MENUS_RESTAURANTE = 'MENUS_RESTAURANTE';
export const AGREGAR_MENU = 'AGREGAR_MENU';
export const VALIDAR_MENU = 'VALIDAR_MENU';
export const ELIMINAR_MENU = 'ELIMINAR_MENU'
export const ESTADO_MENU = "ESTADO_MENU"
export const MENU_ACTUAL = "MENU_ACTUAL";
export const ACTUALIZAR_MENU = 'ACTUALIZAR_MENU'
export const LIMPIAR_MENU = 'LIMPIAR_MENU'


export const SECCIONES_MENU = 'SECCIONES_MENU';
export const AGREGAR_SECCION = 'AGREGAR_SECCION';
export const VALIDAR_SECCION = 'VALIDAR_SECCION';
export const ELIMINAR_SECCION = 'ELIMINAR_SECCION'
export const ESTADO_SECCION = "ESTADO_SECCION"
export const SECCION_ACTUAL = "SECCION_ACTUAL";
export const ACTUALIZAR_SECCION = 'ACTUALIZAR_SECCION'
export const LIMPIAR_SECCION = 'LIMPIAR_SECCION'

export const PLATILLOS_SECCION = 'PLATILLOS_SECCION';
export const AGREGAR_PLATILLO = 'AGREGAR_PLATILLO';
export const VALIDAR_PLATILLO = 'VALIDAR_PLATILLO';
export const ELIMINAR_PLATILLO = 'ELIMINAR_PLATILLO'
export const ESTADO_PLATILLO = "ESTADO_PLATILLO"
export const PLATILLO_ACTUAL = "PLATILLO_ACTUAL";
export const ACTUALIZAR_PLATILLO = 'ACTUALIZAR_PLATILLO'
export const LIMPIAR_PLATILLO = 'LIMPIAR_PLATILLO'

export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';


export const REGISTRO_EXISTOSO = "REGISTRO_EXITOSO";
export const REGISTRO_ERROR = "REGISTRO_ERROR";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGIN_EXITOSO = "LOGIN_EXITOSO";
export const CERRAR_SESION = 'CERRAR_SESION';
export const OBTENER_USUARIO = 'OBTENER_USUARIO';
